package com.example.ecommercecatalogue;

import androidx.appcompat.app.AppCompatActivity;

import android.os.Bundle;

// an incantation for the creation of an Activity
import android.os.Bundle;

import androidx.appcompat.app.AppCompatActivity;
import androidx.recyclerview.widget.LinearLayoutManager;
import androidx.recyclerview.widget.RecyclerView;

import java.util.ArrayList;
import java.util.List;

// inflate/populate the RecyclerView with sample products

public class MainActivity extends AppCompatActivity {

    private RecyclerView recyclerView;      // portal to the parallel dimension of RecyclerView
    private ProductAdapter productAdapter;  // a magical adapter to navigate through the products

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);  // set the stage for our grand performance

        recyclerView = findViewById(R.id.recyclerView);  // scan the universe for the RecyclerView
        recyclerView.setLayoutManager(new LinearLayoutManager(this));  // arrange the cosmic layout

        // create a new List of 'Product' object and initialize it with
        // the data generated by the 'generateSampleData()' method
        List<Product> productList = generateSampleData();
        productAdapter = new ProductAdapter(productList, this);  // craft the adapter with the chosen artifacts
        recyclerView.setAdapter(productAdapter);  // place the adapter into the RecyclerView dimension
    }// end 'onCreate' method

    // A ritual to generate sample data, a glimpse into the unknown products
    // for the domain expansion of the product universe
    private List<Product> generateSampleData() {
        List<Product> productList = new ArrayList<>();
        productList.add(new Product(R.drawable.photo1, "Product 1"));  // unveiling the first artifact
        productList.add(new Product(R.drawable.photo2, "Product 2"));  // discovering the second relic
        productList.add(new Product(R.drawable.photo3, "Product 3"));
        productList.add(new Product(R.drawable.photo4, "Product 4"));
        productList.add(new Product(R.drawable.photo5, "Product 5"));
        productList.add(new Product(R.drawable.photo6, "Product 6"));
        productList.add(new Product(R.drawable.photo7, "Product 7"));
        productList.add(new Product(R.drawable.photo8, "Product 8"));

        return productList;
    }// end 'generateSampleData' method

}// end 'MainActivity' class
